package gui;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class ChangePassword extends javax.swing.JFrame {

    ResultSet rs;
    Statement st;
    server.DBHelper db = new server.DBHelper();
    Connection con = db.getCon();
    boolean flag1 = false, flag2 = false, flag3 = false;

    public ChangePassword(String empNumber, String type) {
        initComponents();
        ImageIcon img = new ImageIcon("image//change_pass.png");
        this.setIconImage(img.getImage());
        lblID.setText(empNumber);
        lblID.setVisible(false);
        lblType.setText(type);
        lblType.setVisible(false);
        btnOK.setEnabled(false);
        txtNewPass.setEnabled(false);
        txtConfirmPass.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOldPass = new javax.swing.JLabel();
        lblNewPass = new javax.swing.JLabel();
        lblConfirmPass = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JPasswordField();
        lblType = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JTextField();
        txtConfirmPass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Old Password:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("New Password:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Confirm Password:");

        lblOldPass.setForeground(new java.awt.Color(255, 0, 0));
        lblOldPass.setText(" ");

        lblNewPass.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        lblNewPass.setForeground(new java.awt.Color(255, 0, 0));
        lblNewPass.setText(" ");

        lblConfirmPass.setForeground(new java.awt.Color(255, 0, 0));
        lblConfirmPass.setText(" ");

        btnOK.setText("Agree");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        lblID.setText("Trống");

        txtOldPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtOldPassCaretUpdate(evt);
            }
        });

        txtNewPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNewPassCaretUpdate(evt);
            }
        });

        txtConfirmPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtConfirmPassCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnOK)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 157, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOldPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblConfirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblID)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOldPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNewPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConfirmPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOK)
                            .addComponent(btnReset))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblType))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtOldPass.setText("");
        txtNewPass.setText("");
        txtConfirmPass.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        int click = JOptionPane.showConfirmDialog(null, "Confirm password change?");
        if (flag1 == true && flag2 == true && flag3 == true && click == 0) {
            try {
                String id;
                if (lblType.getText().equals("Administrator")) {
                    id = "adminNumber";
                } else {
                    id = "empNumber";
                }
                
                st = con.createStatement();
                st.executeUpdate("UPDATE " + lblType.getText() + " SET Password='" + txtConfirmPass.getText() + "' WHERE "+ id + "='" + lblID.getText() + "'");
                JOptionPane.showMessageDialog(null, "Change password is successfully.");
                this.setVisible(false);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error:: SQLException");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Change password is fail!");
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void txtOldPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtOldPassCaretUpdate
        if (txtOldPass.getText().trim().equals("")) {
            lblOldPass.setText(" ");
            btnOK.setEnabled(false);
        } else {
            try {
                String id;
                if (lblType.getText().equals("Administrator")) {
                    id = "adminNumber";
                } else {
                    id = "empNumber";
                }
                
                st = con.createStatement();
                rs = st.executeQuery("Select * from " + lblType.getText() + " where " + id + "= '" + lblID.getText() + "' and Password= '" + txtOldPass.getText() + "'");
                while (true) {
                    if (!rs.next()) {
                        lblOldPass.setText("Wrong Password.");
                        lblOldPass.setForeground(Color.red);
                        flag1 = false;
                        btnOK.setEnabled(false);
                        txtNewPass.setEnabled(false);
                        txtConfirmPass.setEnabled(false);
                        return;
                    } else {
                        lblOldPass.setText("Correct password.");
                        lblOldPass.setForeground(Color.blue);
                        flag1 = true;
                        btnOK.setEnabled(false);
                        txtNewPass.setEnabled(true);
                        txtConfirmPass.setEnabled(true);
                        break;
                    }
                }
            } catch (SQLException e) {
                System.out.println(lblType.getText());
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Error:: SQLException");
            }
        }
    }//GEN-LAST:event_txtOldPassCaretUpdate

    private void txtNewPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNewPassCaretUpdate
        if (txtNewPass.getText().trim().equals("")) {
            lblNewPass.setText(" ");
            btnOK.setEnabled(false);
        } else if (txtNewPass.getText().equals(txtOldPass.getText())) {
            lblNewPass.setText("New password must be different from the old password.");
            lblNewPass.setForeground(Color.red);
            btnOK.setEnabled(false);
        } else {
            char x;
            for (int i = 0; i < txtNewPass.getText().length(); i++) {
                x = txtNewPass.getText().charAt(i);
                if (x == ' ') {
                    lblNewPass.setText("Password cannot contain spaces.");
                    lblNewPass.setForeground(Color.red);
                    flag2 = false;
                    btnOK.setEnabled(false);
                    return;
                }
            }
            while (true) {
                if (txtNewPass.getText().length() < 6 || txtNewPass.getText().length() > 18) {
                    lblNewPass.setText("Password length must be between 6-18 characters.");
                    lblNewPass.setForeground(Color.red);
                    flag2 = false;
                    btnOK.setEnabled(false);
                    return;
                } else {
                    lblNewPass.setText("Valid password.");
                    lblNewPass.setForeground(Color.blue);
                    flag2 = true;
                    btnOK.setEnabled(false);
                    break;
                }
            }
        }
    }//GEN-LAST:event_txtNewPassCaretUpdate

    private void txtConfirmPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtConfirmPassCaretUpdate
        if (txtConfirmPass.getText().trim().equals("")) {
            lblConfirmPass.setText(" ");
            btnOK.setEnabled(false);
        } else {
            while (true) {
                if (!txtConfirmPass.getText().equals(txtNewPass.getText())) {
                    lblConfirmPass.setText("Confirm password must be the same as the password.");
                    lblConfirmPass.setForeground(Color.red);
                    flag3 = false;
                    btnOK.setEnabled(false);
                    return;
                } else {
                    lblConfirmPass.setText("Valid password.");
                    lblConfirmPass.setForeground(Color.blue);
                    flag3 = true;
                    btnOK.setEnabled(true);
                    break;
                }
            }
        }
    }//GEN-LAST:event_txtConfirmPassCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblConfirmPass;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtConfirmPass;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JPasswordField txtOldPass;
    // End of variables declaration//GEN-END:variables
}
