package gui;

import server.DBHelper;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;

public class LoginForm extends javax.swing.JFrame {

    server.DBHelper db = new server.DBHelper();
    
    public LoginForm() {
        initComponents();
        ImageIcon img = new ImageIcon("image//login.png");
        this.setIconImage(img.getImage());
        this.setResizable(false);
        
        lblLogin_logo.setSize(280,280);
        new SetImage().setImageLable(lblLogin_logo, "image//logo2.png");
    }

    public void OK() {
        if (txtLogin_username.getText().equals("") || txtLogin_username.getText().equals("Enter username")) {
            showMessage.setText("Username cann't be blank.");
            txtLogin_username.requestFocus();
            return;
        } else if (txtLogin_password.getText().equals("") || txtLogin_password.getText().equals("Enter password")) {
            showMessage.setText("Password cann't be blank.");
            txtLogin_password.requestFocus();
            return;
        }

        if (cbLogin_role.getSelectedIndex() == 1) {
            try {
                Connection con = db.getCon();
                String admin = "select * from Administrator where AdminNumber=? and password=?";
                PreparedStatement ps = con.prepareStatement(admin);
                ps.setString(1, txtLogin_username.getText());
                ps.setString(2, txtLogin_password.getText());
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    new AdminForm(rs.getString("adminNumber")).setVisible(true);
                    this.setVisible(false);
                } else {
                    txtLogin_password.setText("");
                    txtLogin_password.requestFocus();
                    showMessage.setText("Username or password is incorrect.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error:: Cannot connect to server");
            }
        }
        if (cbLogin_role.getSelectedIndex() == 0) {
            try {
                Connection con = db.getCon();
                String Emp = "select * from Employee where empNumber=? and password=?";
                PreparedStatement ps = con.prepareStatement(Emp);
                ps.setString(1, txtLogin_username.getText());
                ps.setString(2, txtLogin_password.getText());
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    new EmployeeForm(rs.getString("empNumber")).setVisible(true);
                    this.setVisible(false);
                } else {
                    txtLogin_password.setText("");
                    txtLogin_password.requestFocus();
                    showMessage.setText("Username or password is incorrect.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error:: Cannot connect to database");
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLoginBackground = new javax.swing.JPanel();
        panelLoginForm = new javax.swing.JPanel();
        txtLogin_username = new javax.swing.JTextField();
        txtLogin_password = new javax.swing.JPasswordField();
        btnLogin_login = new javax.swing.JButton();
        ckLogin_showPassword = new javax.swing.JCheckBox();
        showMessage = new javax.swing.JLabel();
        cbLogin_role = new javax.swing.JComboBox<>();
        lblLogin_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Transfer Management");
        setBackground(new java.awt.Color(255, 0, 0));
        setMinimumSize(new java.awt.Dimension(460, 600));
        setPreferredSize(new java.awt.Dimension(460, 600));

        panelLoginBackground.setBackground(new java.awt.Color(109, 146, 208));
        panelLoginBackground.setPreferredSize(new java.awt.Dimension(460, 600));

        panelLoginForm.setBackground(new java.awt.Color(255, 255, 255));
        panelLoginForm.setMinimumSize(new java.awt.Dimension(400, 350));
        panelLoginForm.setPreferredSize(new java.awt.Dimension(400, 350));

        txtLogin_username.setBackground(new java.awt.Color(255, 255, 255));
        txtLogin_username.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtLogin_username.setForeground(new java.awt.Color(221, 221, 221));
        txtLogin_username.setText("Enter username");
        txtLogin_username.setToolTipText("");
        txtLogin_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 221, 221), 1, true));
        txtLogin_username.setCaretColor(null);
        txtLogin_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLogin_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLogin_usernameFocusLost(evt);
            }
        });
        txtLogin_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLogin_usernameKeyPressed(evt);
            }
        });

        txtLogin_password.setBackground(new java.awt.Color(255, 255, 255));
        txtLogin_password.setForeground(new java.awt.Color(221, 221, 221));
        txtLogin_password.setText("Enter password");
        txtLogin_password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 221, 221), 1, true));
        txtLogin_password.setName(""); // NOI18N
        txtLogin_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLogin_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLogin_passwordFocusLost(evt);
            }
        });
        txtLogin_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLogin_passwordKeyPressed(evt);
            }
        });

        btnLogin_login.setBackground(new java.awt.Color(24, 119, 242));
        btnLogin_login.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        btnLogin_login.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin_login.setText("Login");
        btnLogin_login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 221, 221), 1, true));
        btnLogin_login.setBorderPainted(false);
        btnLogin_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin_loginActionPerformed(evt);
            }
        });

        ckLogin_showPassword.setBackground(new java.awt.Color(255, 255, 255));
        ckLogin_showPassword.setText("Show password");
        ckLogin_showPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ckLogin_showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckLogin_showPasswordActionPerformed(evt);
            }
        });

        showMessage.setBackground(new java.awt.Color(255, 255, 255));
        showMessage.setForeground(new java.awt.Color(255, 0, 0));

        cbLogin_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Manager" }));
        cbLogin_role.setMinimumSize(new java.awt.Dimension(88, 26));
        cbLogin_role.setPreferredSize(new java.awt.Dimension(88, 26));
        cbLogin_role.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbLogin_roleKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginFormLayout = new javax.swing.GroupLayout(panelLoginForm);
        panelLoginForm.setLayout(panelLoginFormLayout);
        panelLoginFormLayout.setHorizontalGroup(
            panelLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginFormLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckLogin_showPassword)
                    .addComponent(btnLogin_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLogin_username, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(txtLogin_password)
                    .addComponent(showMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLogin_role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelLoginFormLayout.setVerticalGroup(
            panelLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginFormLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtLogin_username, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(txtLogin_password, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbLogin_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(ckLogin_showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 33, Short.MAX_VALUE)
                .addComponent(showMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin_login, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLoginBackgroundLayout = new javax.swing.GroupLayout(panelLoginBackground);
        panelLoginBackground.setLayout(panelLoginBackgroundLayout);
        panelLoginBackgroundLayout.setHorizontalGroup(
            panelLoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginBackgroundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogin_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        panelLoginBackgroundLayout.setVerticalGroup(
            panelLoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginBackgroundLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblLogin_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(panelLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLoginBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLoginBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ckLogin_showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckLogin_showPasswordActionPerformed
        if (ckLogin_showPassword.isSelected()) {
            txtLogin_password.setEchoChar((char) 0);
        } else {
            txtLogin_password.setEchoChar('*');
        }
    }//GEN-LAST:event_ckLogin_showPasswordActionPerformed

    private void txtLogin_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLogin_usernameFocusGained
        if (txtLogin_username.getText().equals("Enter username")) {
            txtLogin_username.setText("");
            txtLogin_username.setForeground(Color.BLACK);
        } 
    }//GEN-LAST:event_txtLogin_usernameFocusGained

    private void txtLogin_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLogin_usernameFocusLost
        if (txtLogin_username.getText().equals("")) {
            txtLogin_username.setText("Enter username");
            txtLogin_username.setForeground(Color.decode("#DDDDDD"));
        } 
    }//GEN-LAST:event_txtLogin_usernameFocusLost

    private void txtLogin_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLogin_passwordFocusGained
        if (txtLogin_password.getText().equals("Enter password")) {
            txtLogin_password.setText("");
            txtLogin_password.setForeground(Color.BLACK);
        } 
    }//GEN-LAST:event_txtLogin_passwordFocusGained

    private void txtLogin_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLogin_passwordFocusLost
        if (txtLogin_password.getText().equals("")) {
            txtLogin_password.setText("Enter password");
            txtLogin_password.setForeground(Color.decode("#DDDDDD"));
        }
    }//GEN-LAST:event_txtLogin_passwordFocusLost

    private void btnLogin_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin_loginActionPerformed
        OK();
    }//GEN-LAST:event_btnLogin_loginActionPerformed

    private void cbLogin_roleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbLogin_roleKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            OK();
        }
    }//GEN-LAST:event_cbLogin_roleKeyPressed

    private void txtLogin_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLogin_passwordKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            OK();
        }
    }//GEN-LAST:event_txtLogin_passwordKeyPressed

    private void txtLogin_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLogin_usernameKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            OK();
        }
    }//GEN-LAST:event_txtLogin_usernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin_login;
    private javax.swing.JComboBox<String> cbLogin_role;
    private javax.swing.JCheckBox ckLogin_showPassword;
    private javax.swing.JLabel lblLogin_logo;
    private javax.swing.JPanel panelLoginBackground;
    private javax.swing.JPanel panelLoginForm;
    private javax.swing.JLabel showMessage;
    private javax.swing.JPasswordField txtLogin_password;
    private javax.swing.JTextField txtLogin_username;
    // End of variables declaration//GEN-END:variables
}
