package i18nsearchform;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author gamin
 */
public class i18nSearchForm extends javax.swing.JFrame {

    /**
     * Creates new form i18nSearchForm
     */
    public i18nSearchForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblKeywords = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblVi = new javax.swing.JLabel();
        lblJapan = new javax.swing.JLabel();
        lblFr = new javax.swing.JLabel();
        lblUs = new javax.swing.JLabel();
        lblRu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Internationalization");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i18nsearchform/Globe-icon.png"))); // NOI18N

        lblKeywords.setText("Keywords");

        btnSearch.setText("Search");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblVi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i18nsearchform/flag_vietnam.png"))); // NOI18N
        lblVi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViMouseClicked(evt);
            }
        });

        lblJapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i18nsearchform/Japan-flag.png"))); // NOI18N
        lblJapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJapanMouseClicked(evt);
            }
        });

        lblFr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i18nsearchform/french_icon.jpg"))); // NOI18N
        lblFr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFrMouseClicked(evt);
            }
        });

        lblUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i18nsearchform/us_flag.jpeg"))); // NOI18N
        lblUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsMouseClicked(evt);
            }
        });

        lblRu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i18nsearchform/russian_flag.gif"))); // NOI18N
        lblRu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblKeywords)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(109, Short.MAX_VALUE)
                        .addComponent(lblVi)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblJapan)
                                .addGap(30, 30, 30)
                                .addComponent(lblFr)
                                .addGap(30, 30, 30)
                                .addComponent(lblUs)))
                        .addGap(30, 30, 30)
                        .addComponent(lblRu)))
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(229, 229, 229))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKeywords)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnReset))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRu)
                    .addComponent(lblUs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVi)
                    .addComponent(lblJapan))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblViMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViMouseClicked
        Locale current = new Locale("vi", "VN");
        ResourceBundle rb = ResourceBundle.getBundle("i18nsearchForm/i18n/newproperties", current);
        lblKeywords.setText(rb.getString("label"));
        btnSearch.setText(rb.getString("btnSearch"));
        btnReset.setText(rb.getString("btnReset"));
        setTitle(rb.getString("title"));
    }//GEN-LAST:event_lblViMouseClicked

    private void lblJapanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJapanMouseClicked
        Locale current = new Locale("ja", "JP");
        ResourceBundle rb = ResourceBundle.getBundle("i18nsearchForm/i18n/newproperties", current);
        lblKeywords.setText(rb.getString("label"));
        btnSearch.setText(rb.getString("btnSearch"));
        btnReset.setText(rb.getString("btnReset"));
        setTitle(rb.getString("title"));
    }//GEN-LAST:event_lblJapanMouseClicked

    private void lblFrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFrMouseClicked
        Locale current = new Locale("fr", "FR");
        ResourceBundle rb = ResourceBundle.getBundle("i18nsearchForm/i18n/newproperties", current);
        lblKeywords.setText(rb.getString("label"));
        btnSearch.setText(rb.getString("btnSearch"));
        btnReset.setText(rb.getString("btnReset"));
        setTitle(rb.getString("title"));
    }//GEN-LAST:event_lblFrMouseClicked

    private void lblUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsMouseClicked
        Locale current = new Locale("en", "US");
        ResourceBundle rb = ResourceBundle.getBundle("i18nsearchForm/i18n/newproperties", current);
        lblKeywords.setText(rb.getString("label"));
        btnSearch.setText(rb.getString("btnSearch"));
        btnReset.setText(rb.getString("btnReset"));
        setTitle(rb.getString("title"));
    }//GEN-LAST:event_lblUsMouseClicked

    private void lblRuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRuMouseClicked
        Locale current = new Locale("ru", "RU");
        ResourceBundle rb = ResourceBundle.getBundle("i18nsearchForm/i18n/newproperties", current);
        lblKeywords.setText(rb.getString("label"));
        btnSearch.setText(rb.getString("btnSearch"));
        btnReset.setText(rb.getString("btnReset"));
        setTitle(rb.getString("title"));
    }//GEN-LAST:event_lblRuMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtSearch.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(i18nSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(i18nSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(i18nSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(i18nSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new i18nSearchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblFr;
    private javax.swing.JLabel lblJapan;
    private javax.swing.JLabel lblKeywords;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRu;
    private javax.swing.JLabel lblUs;
    private javax.swing.JLabel lblVi;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
